# Generated by Django 5.2.9 on 2026-02-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0004_review_seller_alter_property_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrLivArea', models.IntegerField()),
                ('YearBuilt', models.IntegerField()),
                ('GarageCars', models.IntegerField()),
                ('TotalBsmtSF', models.IntegerField()),
                ('FullBath', models.IntegerField()),
                ('OverallQual', models.IntegerField()),
                ('Neighborhood', models.CharField(max_length=50)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
